[profile.default]
opt-level = 3
lto = true
linker = 'mold'
jobs = 16
use = [
  'bluetooth', 'vaapi', 'zsh',
  '-doc', '-test', '-systemd'
]

[profile.fast-compile]
opt-level = 2
lto = false


[system]
gpu = 'intel'
cpu_flags = [
  'aes', 'avx', 'f16c', 'fma3', 'mmx', 'mmxext', 'pclmul', 'popcnt', 'rdrand',
  'sha', 'sse', 'sse2', 'sse3', 'sse4_1', 'sse4_2', 'ssse3'
]

[package]
# If string, then it is use
# If table, then has keys 'use, cflags, ldflags'
iwd = 'standalone'
sway = [ '-swaynag', '-swaybar' ]
efivar = { linker = 'ld' }